general {
    lock_cmd = pidof hyprlock || hyprlock
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
    timeout = 900                               # 15min
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
    timeout = 14400                             # 4h
    on-timeout = loginctl lock-session          # lock screen when timeout has passed
}
