local map = vim.keymap.set
local fzf = require("fzf-lua")

map("i", "jk", "<Esc>", { desc = "Exit insert mode" })
map("n", "<leader>nh", "<cmd>nohlsearch<cr>", { desc = "Clear search highlights" })
map("n", "x", '"_x', { desc = "Delete character without yanking" })
map("v", ">", ">gv", { desc = "Increase indentation" })
map("v", "<", "<gv", { desc = "Decrease indentation" })
map("n", "<C-d>", "<C-d>zz", { desc = "Scroll down and center" })
map("n", "<C-u>", "<C-u>zz", { desc = "Scroll up and center" })
map("n", "n", "nzzzv", { desc = "Next search result" })
map("n", "N", "Nzzzv", { desc = "Previous search result" })

map("n", "<leader>sv", "<C-w>v", { desc = "Vertical split" })
map("n", "<leader>sh", "<C-w>s", { desc = "Horizontal split" })
map("n", "<leader>se", "<C-w>=", { desc = "Equalize splits" })
map("n", "<leader>sx", "<cmd>close<cr>", { desc = "Close split" })
map("n", "<C-h>", "<C-w>h", { desc = "Focus left split" })
map("n", "<C-j>", "<C-w>j", { desc = "Focus lower split" })
map("n", "<C-k>", "<C-w>k", { desc = "Focus upper split" })
map("n", "<C-l>", "<C-w>l", { desc = "Focus right split" })
map("n", "<leader>to", "<cmd>tabnew<cr>", { desc = "New tab" })
map("n", "<leader>tx", "<cmd>tabclose<cr>", { desc = "Close tab" })
map("n", "<leader>q", "<cmd>bp|bd #<cr>", { desc = "Close buffer" })
map("n", "<leader>tp", "<cmd>BufferLinePick<cr>", { desc = "Pick buffer" })
map("n", "<leader>tc", "<cmd>BufferLinePickClose<cr>", { desc = "Pick buffer to close" })
map("n", "<S-l>", "<cmd>BufferLineCycleNext<cr>", { desc = "Next buffer" })
map("n", "<S-h>", "<cmd>BufferLineCyclePrev<cr>", { desc = "Previous buffer" })

map({ "n", "v" }, "<leader>cf", function()
	require("conform").format({ lsp_format = "fallback", timeout_ms = 3000 })
end, { desc = "Format file or range" })
map("n", "<leader>sf", function()
	local prior = vim.b.disable_autoformat
	vim.b.disable_autoformat = true
	local ok, err = pcall(vim.cmd.write)
	vim.b.disable_autoformat = prior
	if not ok then
		error(err)
	end
end, { desc = "Save without formatting" })
map("n", "<leader>ct", "<cmd>FormatToggle<cr>", { desc = "Toggle buffer format-on-save" })

map("n", "ge", vim.diagnostic.open_float, { desc = "Line diagnostics" })
map("n", "[d", function()
	vim.diagnostic.jump({ count = -1, float = true })
end, { desc = "Previous diagnostic" })
map("n", "]d", function()
	vim.diagnostic.jump({ count = 1, float = true })
end, { desc = "Next diagnostic" })
map("n", "gH", function()
	local enabled = vim.lsp.inlay_hint.is_enabled({ bufnr = 0 })
	vim.lsp.inlay_hint.enable(not enabled, { bufnr = 0 })
end, { desc = "Toggle inlay hints" })
map("n", "gd", vim.lsp.buf.definition, { desc = "Go to definition" })
map("n", "gD", vim.lsp.buf.declaration, { desc = "Go to declaration" })
map("n", "gi", vim.lsp.buf.implementation, { desc = "Go to implementation" })
map("n", "grr", vim.lsp.buf.references, { desc = "References" })
map("n", "K", vim.lsp.buf.hover, { desc = "Hover documentation" })
map({ "n", "v" }, "<leader>ca", fzf.lsp_code_actions, { desc = "Code action" })
map("n", "<leader>cr", vim.lsp.buf.rename, { desc = "Rename symbol" })

map("n", "<leader>ff", fzf.files, { desc = "Find files" })
map("n", "<leader>fs", fzf.live_grep, { desc = "Live grep" })
map("n", "<leader>fb", fzf.grep_cword, { desc = "Grep word" })
map("n", "<leader>fr", fzf.oldfiles, { desc = "Recent files" })
map("n", "<leader>fh", fzf.help_tags, { desc = "Help tags" })
map("n", "<leader>fc", function()
	fzf.files({ cwd = vim.fn.stdpath("config") })
end, { desc = "Find config files" })
map("n", "<leader>e", "<cmd>NvimTreeToggle<cr>", { desc = "Toggle file explorer" })
map("n", "<leader>E", "<cmd>NvimTreeFindFile<cr>", { desc = "Reveal current file" })

map("n", "<leader>gv", "<cmd>CodeDiff<cr>", { desc = "Review repository changes" })
map("n", "<leader>gS", "<cmd>CodeDiff --staged<cr>", { desc = "Review staged changes" })
map("n", "<leader>gf", "<cmd>CodeDiff file HEAD<cr>", { desc = "Review current file" })
map("n", "<leader>gh", "<cmd>CodeDiff history %<cr>", { desc = "Current file history" })

map("n", "<leader>S", function()
	require("grug-far").toggle_instance({ instanceName = "search-replace" })
end, { desc = "Toggle search and replace" })
map({ "n", "v" }, "<leader>sw", function()
	require("grug-far").open({ prefills = { search = vim.fn.expand("<cword>") } })
end, { desc = "Replace word" })
map("n", "<leader>sp", function()
	require("grug-far").open({ prefills = { paths = vim.fn.expand("%") } })
end, { desc = "Replace in file" })

map("n", "<leader>lg", function()
	local path = vim.api.nvim_buf_get_name(0)
	local root = vim.fs.root(path ~= "" and path or vim.uv.cwd(), ".git") or vim.uv.cwd()
	vim.cmd("botright 15new")
	vim.fn.jobstart({ "lazygit", "--path", root }, { term = true })
	vim.cmd.startinsert()
end, { desc = "LazyGit" })

map({ "n", "v" }, "<leader>cc", "<cmd>CodeCopy<cr>", { desc = "Copy code" })
map("n", "<leader>cp", "<cmd>Copilot panel<cr>", { desc = "Copilot panel" })
map("n", "<leader>cs", "<cmd>Copilot status<cr>", { desc = "Copilot status" })
map("n", "<leader>cT", function()
	require("copilot.suggestion").toggle_auto_trigger()
end, { desc = "Toggle Copilot suggestions" })

map("n", "<leader>xx", "<cmd>Trouble diagnostics toggle<cr>", { desc = "Diagnostics" })
map("n", "<leader>xX", "<cmd>Trouble diagnostics toggle filter.buf=0<cr>", { desc = "Buffer diagnostics" })
map("n", "<leader>xs", "<cmd>Trouble symbols toggle focus=false<cr>", { desc = "Symbols" })
map("n", "<leader>xq", "<cmd>Trouble qflist toggle<cr>", { desc = "Quickfix" })
map("n", "<leader>xc", function()
	local line = vim.api.nvim_win_get_cursor(0)[1]
	local diagnostics = vim.diagnostic.get(0, { lnum = line - 1 })
	if #diagnostics == 0 then
		vim.notify("No diagnostics on the current line", vim.log.levels.INFO)
		return
	end

	table.sort(diagnostics, function(a, b)
		return (a.severity or vim.diagnostic.severity.HINT) < (b.severity or vim.diagnostic.severity.HINT)
	end)

	local messages = vim.tbl_map(function(diagnostic)
		return diagnostic.message:gsub("%s*\n%s*", " ")
	end, diagnostics)
	local filename = vim.api.nvim_buf_get_name(0)
	filename = filename == "" and "[No Name]" or vim.fn.fnamemodify(filename, ":.")
	local text = string.format(
		"File: %s\nLine: %d\nDiagnostic%s:\n%s",
		filename,
		line,
		#messages == 1 and "" or "s",
		table.concat(messages, "\n")
	)

	vim.fn.setreg("+", text)
	vim.notify("Copied line diagnostics to the clipboard")
end, { desc = "Copy line diagnostics" })

local dap = require("dap")
map("n", "<F5>", dap.continue, { desc = "Debug continue" })
map("n", "<F10>", dap.step_over, { desc = "Debug step over" })
map("n", "<F11>", dap.step_into, { desc = "Debug step into" })
map("n", "<F12>", dap.step_out, { desc = "Debug step out" })
map("n", "<leader>db", dap.toggle_breakpoint, { desc = "Toggle breakpoint" })
map("n", "<leader>dt", dap.terminate, { desc = "Stop debugger" })
map("n", "<leader>du", function()
	require("dapui").toggle()
end, { desc = "Toggle debugger UI" })
map("n", "<leader>dl", function()
	require("osv").launch({ port = 8086 })
end, { desc = "Launch Lua debug server" })

map({ "x", "o" }, "af", function()
	require("nvim-treesitter-textobjects.select").select_textobject("@function.outer", "textobjects")
end, { desc = "Outer function" })
map({ "x", "o" }, "if", function()
	require("nvim-treesitter-textobjects.select").select_textobject("@function.inner", "textobjects")
end, { desc = "Inner function" })
map({ "x", "o" }, "ac", function()
	require("nvim-treesitter-textobjects.select").select_textobject("@class.outer", "textobjects")
end, { desc = "Outer class" })
map({ "x", "o" }, "ic", function()
	require("nvim-treesitter-textobjects.select").select_textobject("@class.inner", "textobjects")
end, { desc = "Inner class" })

map("n", "<leader>md", "<cmd>RenderMarkdown toggle<cr>", { desc = "Toggle Markdown rendering" })
map("n", "<leader>mp", "<cmd>RenderMarkdown preview<cr>", { desc = "Preview Markdown" })
map("n", "<leader>ns", require("package-info").show, { desc = "Show dependency versions" })
map("n", "<leader>nt", require("package-info").toggle, { desc = "Toggle dependency versions" })
map("n", "<leader>nu", require("package-info").update, { desc = "Update dependency" })
